---
title: "First Knit"
author: "Your Name"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I am currently attending Quartz Hill High school as a junior. My English teacher is Mr. Mahady and I have a good grade in his class, but English has never been my best subject. Mrs. Benavides is my Math teacher and I have a good grade in her class; however, I feel much more confident in Math than English.
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
I have a computer at home that runs on the Windows operating system. On a scale from 1 to 10, I feel confidently in operating my computer as a 7/10. I have internet access that maintains a fairly good connection.

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   
 
I prefer to be called by my name: Riley.



## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   
 I want to achieve a comfortable, happy life. I currently do not know what subject exactly I want to pursue in college; however, I am debating between something regarding Finance, Astrophysics, or engineering. I plan on achieving a master's or doctorate degree.




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   
  
I have been on a trip to Italy once, visiting Rome, the Vatican, Venace, and many other popular tourist locations in the area. I have never been in the military, but I scored well on the ASVAB so I have the option to in the future. I would most likely choose the space force, a new branch of military, because I am interested in that field of research.



## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
I am currently taking math 115, and I had no clue math 116 existed. I plan on getting an A in all of my classes in order to keep options open since i am still undecided on my field of study.






  




